# Generated by Django 3.1.3 on 2021-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarket',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
